### ISSUE TITLE
[BUG] RangeError when selection.isValid is false

### ISSUE THREAD

**Issue by MiniSuperDev** [xsahil03x/multi_trigger_autocomplete#11]
https://github.com/xsahil03x/multi_trigger_autocomplete/blob/751988a10b0b8f5b10bb0f2a8bf88d7abaf2bbab/lib/src/autocomplete_trigger.dart#L69

```dart
Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 0..21: -1
```
When isValid is false baseOffset and other properties are -1

So 
https://github.com/xsahil03x/multi_trigger_autocomplete/blob/751988a10b0b8f5b10bb0f2a8bf88d7abaf2bbab/lib/src/autocomplete_trigger.dart#L63-L65

I fixed it like this:

```dart
  AutocompleteQuery? invokingTrigger(TextEditingValue textEditingValue) {
    if (!textEditingValue.selection.isValid) {
      return null;
    }

    final text = textEditingValue.text;
    final cursorPosition = textEditingValue.selection.baseOffset;
```

In my case it happens that `selection.isValid` is `false` when the Widget is a child of a custom SliverReorderableList and I change its position by drag and drop.

**Comment by xsahil03x** [comment]
Hey @MiniSuperDev, can you also share a small reproducible code which I can test this on?

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/multi_trigger_autocomplete/commit/3c1a152f65bf0c8c56f9e5ea5fe3ebffb85119a3
