### ISSUE TITLE
An issue with multiline keyboard 

### ISSUE THREAD

**Issue by iammuho** [xsahil03x/multi_trigger_autocomplete#12]
Hello,

I've a strange bug with multiline-keyboard.

```
TextField(
            focusNode: focusNode,
            controller: c,
            key: const Key('contentForm_contentInput_textField'),
            onChanged: controller.onContentChanged,
            keyboardType: TextInputType.multiline,
            minLines: 1,
            maxLines: 200,
```

When I clicked return(so new line happened), auto-suggestion doesn;t work, but for the first line only it works.

How can i resolve this issue ?

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/multi_trigger_autocomplete/commit/0edb42a9037bc8370d9771eaaf2a49acc78edec6
