### ISSUE TITLE
Can you possibly give me flutter 3.3.3 version?

### ISSUE THREAD

**Issue by Govindbetterlives** [xsahil03x/multi_trigger_autocomplete#18]
Can you possibly give me multi_trigger_autocomplete widget for Flutter 3.3.3 version.

**Comment by xsahil03x** [comment]
@Govindbetterlives I already supports the range [flutter: ">=3.3.0"](https://github.com/xsahil03x/multi_trigger_autocomplete/blob/master/pubspec.yaml#L10). Can you specify your problem a bit more?

**Comment by Govindbetterlives** [comment]
Thanks for the quick reply sir,
It's showing an error like this.

/D:/flutter_sources/flutter_3.3.3/.pub-cache/hosted/pub.dartlang.org/multi_trigger_autocomplete-1.0.0/lib/src/multi_trigger_autocomplete.dart:420:15: Error: The method 'TextFieldTapRegion' isn't defined for the class 'MultiTriggerAutocompleteState'.
 - 'MultiTriggerAutocompleteState' is from 'package:multi_trigger_autocomplete/src/multi_trigger_autocomplete.dart'
 ('/D:/flutter_sources/flutter_3.3.3/.pub-cache/hosted/pub.dartlang.org/multi_trigger_autocomplete-1.0.0/lib/src/multi_trigger_autocomplete.dart') .
Try correcting the name to the name of an existing method, or defining a method named 'TextFieldTapRegion'.
            ? TextFieldTapRegion(
              ^^^^^^^^^^^^^^^^^^

**Comment by xsahil03x** [comment]
Hey @Govindbetterlives you can use the previous version for flutter 3.3.0.
```yaml
dependencies:
  multi_trigger_autocomplete: ^0.1.1
```

**Comment by Govindbetterlives** [comment]
Hi sir,
The error came like this.

Another exception was thrown: Error: Could not find a Portal above this PortalTarget(debugName: null, portalCandidateLabels=[PortalLabel.main]). 

![image](https://github.com/xsahil03x/multi_trigger_autocomplete/assets/81243940/05be56bf-22e1-44a5-bd4a-e45269529f4d)

**Comment by xsahil03x** [comment]
Hey, looks like you missed this [step](https://github.com/xsahil03x/multi_trigger_autocomplete#usage).

You can check the example here: https://github.com/xsahil03x/multi_trigger_autocomplete/blob/master/example/lib/main.dart#L16-L30

**Comment by Govindbetterlives** [comment]
Sorry for disturb,
The options list is to overlay another widget.

![image](https://github.com/xsahil03x/multi_trigger_autocomplete/assets/81243940/748e2a40-a0c1-4703-b1ee-202a330cb068)

**Comment by xsahil03x** [comment]
@Govindbetterlives you need to add the Portal at the very top of the widget tree. Can you share your code somewhere i can look?

**Comment by Govindbetterlives** [comment]
Hi, 
Now is working well. And also can you show the chip widget inside the textfield?

Something like this
![image](https://github.com/fayeed/flutter_mentions/assets/81243940/656741ce-db9f-4a16-ba0a-425059bb821f)

**Comment by xsahil03x** [comment]
@Govindbetterlives this is out of the scope of the package. You can use another library and just switch the `textfield` using [fieldViewBuilder](https://github.com/xsahil03x/multi_trigger_autocomplete/blob/master/lib/src/multi_trigger_autocomplete.dart#L107-L113)

**Comment by Govindbetterlives** [comment]
Hi sir,
Can you help me how to show list and display chip input inside the textfield.
If you help me. you will save my life.

![256438502-656741ce-db9f-4a16-ba0a-425059bb821f](https://github.com/xsahil03x/multi_trigger_autocomplete/assets/81243940/d3971eac-e2a1-4cc9-982d-2aa5be72e382)

**Comment by xsahil03x** [comment]
@Govindbetterlives I guess you can follow this video.
https://www.youtube.com/watch?v=_X9WOy5F1Lo&ab_channel=SuperDeclarative%21
