### ISSUE TITLE
Add custom widget in text field

### ISSUE THREAD

**Issue by MichalNemec** [xsahil03x/multi_trigger_autocomplete#8]
**Is your feature request related to a problem? Please describe.**
Im missing a feature to add custom widget in textfield (i.e. #dart) shows hastags, upon clicking, it adds it, i would like to have chip that holds another data inside.

**Describe the solution you'd like**
upon clicking on autocompleted findings -> save to text #dart:123 (chosen String by developer) but shows custom widget.

**Describe alternatives you've considered**
https://pub.dev/packages/extended_text_field but its chaotic and no clear way.

**Additional context**
i want exactly discord behavior with @ sign (they show @name but holds internally userid)

**Comment by xsahil03x** [comment]
Hey @MichalNemec, can you share a sample UI around your request?

**Comment by MichalNemec** [comment]
I actually managed to make it happen in extended_text_field, grabbed @mention and modified it to my needs. So there is no need from your side. It actually makes sense what you did with this library. Its up to the user to manipulate content in textfield. So sorry to bother you.
