### ISSUE TITLE
Attach multi trigger to scaffold

### ISSUE THREAD

**Issue by MichalNemec** [xsahil03x/multi_trigger_autocomplete#9]
**Is your feature request related to a problem? Please describe.**
Textarea with minlines 10 and maxlines 20 has potential problem to not show autocomplete, if the textarea covers entire user screen.

**Describe the solution you'd like**
attach it to bottom, right above keyboard.

**Describe alternatives you've considered**
tried topStart and bottomEnd if else, but since i have it responsive, its much harder to know where to place it.

**Additional context**
its for blog post and the user needs bigger input field to see more text, which is problematic with showing autocomplete data.

**Comment by MichalNemec** [comment]
my idea was to "glue" the autocomplete to scaffold on top or bottom, so its visible all the time over anything (like appbar is)
but as a workaround i shrunk the maxlines and its good, another idea was to "glue" the autocomplete above the specific word, not on the input itself, exactly like github does.. just write the hashtag symbol in here in reply and you will see what i mean.

**Comment by xsahil03x** [comment]
Hey @MichalNemec, in order to "glue" the autocomplete above a specific word requires a custom implementation of the TextField, which is out of the scope for this package.

Thanks.
